### ISSUE TITLE
RLIPP error

### ISSUE THREAD

**Issue by phdstudent-oje** [aksinghal5590/nest_drugcell#9]
Hi @aksinghal5590

I executed the codes for RLIPP. 
But, I got this error. 

```
(pytorch3drugcell) miruware@devbox:/data6/jihye/Tools/drugcell_rlipp$ python -u ${homedir}/src/rlipp_helper.py -hidden $hidden -ontology $ontology -drug_index $drug_index -gene_index $gene_index -cell_index $cell_index -cell_mutation $cell_mutation -output $output -test $test -predicted $predicted -cpu_count $cpu_count -drug_count 0 -genotype_hiddens 6 > ${homedir}/out_0714.log
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/miruware/anaconda3/envs/pytorch3drugcell/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/miruware/anaconda3/envs/pytorch3drugcell/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/miruware/anaconda3/envs/pytorch3drugcell/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/miruware/anaconda3/envs/pytorch3drugcell/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/data6/jihye/Tools/drugcell_rlipp/src/rlipp_calculator.py", line 142, in calc_term_rlipp
    p_rho = self.exec_lm(X_parent, y)
  File "/data6/jihye/Tools/drugcell_rlipp/src/rlipp_calculator.py", line 131, in exec_lm
    regr.fit(X, y)
  File "/home/miruware/anaconda3/envs/pytorch3drugcell/lib/python3.7/site-packages/sklearn/linear_model/_ridge.py", line 2053, in fit
    gs.fit(X, y, sample_weight=sample_weight)
  File "/home/miruware/anaconda3/envs/pytorch3drugcell/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 891, in fit
    self._run_search(evaluate_candidates)
  File "/home/miruware/anaconda3/envs/pytorch3drugcell/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 1392, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/home/miruware/anaconda3/envs/pytorch3drugcell/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 851, in evaluate_candidates
    enumerate(candidate_params), enumerate(cv.split(X, y, groups))
  File "/home/miruware/anaconda3/envs/pytorch3drugcell/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 337, in split
    ).format(self.n_splits, n_samples)
ValueError: Cannot have number of splits n_splits=5 greater than the number of samples: n_samples=1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data6/jihye/Tools/drugcell_rlipp/src/rlipp_helper.py", line 28, in <module>
    main()
  File "/data6/jihye/Tools/drugcell_rlipp/src/rlipp_helper.py", line 24, in main
    rlipp_calculator.calc_scores()
  File "/data6/jihye/Tools/drugcell_rlipp/src/rlipp_calculator.py", line 166, in calc_scores
    results = parallel(delayed(self.calc_term_rlipp)(feature_map[term], child_feature_map[term], drug_pos_map[drug], term, drug) for term in self.terms)
  File "/home/miruware/anaconda3/envs/pytorch3drugcell/lib/python3.7/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/home/miruware/anaconda3/envs/pytorch3drugcell/lib/python3.7/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/miruware/anaconda3/envs/pytorch3drugcell/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: Cannot have number of splits n_splits=5 greater than the number of samples: n_samples=1.
```

I think "exec_lm definition" cause the error in rlipp_caculator.py.
def exec_lm(self, X, y):
		regr = RidgeCV(cv=5)
		regr.fit(X, y)
		y_pred = regr.predict(X)
		return stats.spearmanr(y_pred, y)[0]

Would you help me please? 

Thanks. Oh.

**Comment by aksinghal5590** [comment]
The problem is you have fewer samples than cross cv. Number of samples in X should be much more than 5.
